title: FIFA 2018
author: EdgarVaguencia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a result match obout fifa wolrd cup 2018

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
